### ISSUE TITLE
Security: can an attacker take Kin from the server using the pay/ endpoint call?

### ISSUE THREAD

**Issue by skyf0xx** [kinecosystem/kin-python-bootstrap#9]
Just wondering what would stop an attacker from:
1. Downloading an app that uses the bootstrap
2. Figuring out the base-url of the endpoint
3. Calling the pay/ endpoint for Kin from the server to be sent to him

it should be simple enough to brute-force the port number

**Comment by Ronserruya** [comment]
You are correct, this server can easily be attacked. The bootstrap does not come with any security. Please refer to this announcement.

https://medium.com/kinblog/the-kin-python-bootstrap-cdd0c320df6b

```
One thing to always keep in mind when developing with Kin is that security is extremely important. This bootstrap does not come with an out-of-the-box security solution. If you are planning to use this bootstrap in production then please make sure to:

Always develop keeping best security practices in mind
Never call the API from your users’ [client] device
Always call the API from your own secured backend server
```

So this is just a microservice to be called from another server

**Comment by skyf0xx** [comment]
Ah of course - thanks this makes sense now. So I would have to call my server, then my server can screen for security, then it can call the bootstrap.
